name = "tigerbuzz-api"
main = "src/index.js"
compatibility_date = "2024-09-23"

[vars]
ALLOWED_ORIGIN = "https://simonsunikanamn.github.io"

[[d1_databases]]
binding = "DB"
database_name = "tigerbuzz"
database_id = "ed0582ba-15b9-43a3-92d4-abe9086812d7"
